# .github/workflows/install-nginx-selfhosted.yml
name: Install Nginx on Self-Hosted Runner

on:
  push:
    branches: [ main ]

jobs:
  install-nginx:
    runs-on: self-hosted  # Target your self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: SSH to the remote server
      run: |
        ssh -tt -i ~/.ssh/id_gitcicd satish@192.168.1.71 "sudo apt update && sudo apt install nginx"
        sudo apt update
        sudo apt install nginx
        EOF
    - name: Update APT and Install Nginx
      run: |
        sudo apt update
        sudo apt install -y nginx

    - name: Start and Enable Nginx
      run: |
        sudo systemctl start nginx
        sudo systemctl enable nginx

    - name: Check Nginx Status
      run: sudo systemctl status nginx

    - name: Test Nginx is Running
      run: curl -I http://localhost

    - name: Testing echo
      run: echo hello world > README.md 
